### ISSUE TITLE
Fails to start-up

### ISSUE THREAD

**Issue by kubo6472** [theo-brown/csgo-get5-docker#1]
Loading Steam API...src/common/opensslconnection.cpp (1616) : unable to load trusted SSL root certificates

**Comment by theo-brown** [comment]
Ah yes I think this is because one version got pushed to DockerHub with ca-certificates removed.
Did you clone the image from DockerHub or build from source?

**Comment by theo-brown** [comment]
I'm pushing an updated version now, should be done in about 30-40 minutes

**Comment by kubo6472** [comment]
cloned the image, thanks, will wait then

**Comment by theo-brown** [comment]
Sorry for the delay, the image on `theobrown/csgo-get5-docker:latest` or `theobrown/csgo-get5-docker:13806` should be working now. Let me know if you have any issues.
